config/routes.rb
Rails.application.routes.draw do

  resources :categories, :elements

  root to: "categories#index"

  get "/allcategories", to: redirect("/")

  get "/elements/:id/toggle_featured", to: "elements#toggle_featured", as: :toggle_featured

  get "/special_elements", to: "elements#special_elements"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :elements
end

app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :category

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController

  before_action :fetch_element, only: [ :show, :edit, :update, :destroy, :toggle_featured ]
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @element }
    end

  end

  def index
    @elements = Element.all

    respond_to do |format|
      format.html
      format.json { render json: @elements }
    end

  end

  def new

  end

  def edit

  end

  def update

  end

  def destroy

  end


  def toggle_featured
    #flips feature value
    @element.toggle!( :featured )
    #message for succesful change
    flash[:notice] = "Succesful change"
    redirect_to @element
  end

  def special_elements
    session[:vip] = true
    redirect_to root_path
  end

  private
    def fetch_element
      @element = Element.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/categories/index.html.erb
<h1> Element Categories </h1>

<ul>
  <% @categories.each do |category| %>
    <li> <%= link_to category.name, category %> (<%= category.elements.count %>) </li>
  <% end %>

  <!-- Element showing special element -->
  <% if session[:vip] %>
       <li>Special Glass Element</li>
  <% end %>

<!-- This is the end -->

</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %> </h1>

<ul>
  <% @category.elements.each do |element| %>
    <li><%= link_to element.name, element %></li>
  <% end %>
</ul>

<p><%= link_to "Back to Element Categories", categories_path %> </p>

app/views/elements/show.html.erb
<h1> <%= @element.name %> </h1>

<% if @element.featured? %>
<p> This is special element </p>
<% else %>
<p> This is non-special element </p>
<%  end %>

<!-- checking if user is admin -->
<% if params[:admin] == "true" %>
    <!-- toggle the feature of element -->
    <p><%= link_to "Toggle featured", toggle_featured_path(@element) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreExercise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- flash message from toggle featured -->
<% if flash[:notice] %>
    <p><%= flash[:notice] %> </p>
<% end %>

<%= yield %>

</body>
</html>